### PR TITLE
DS18B20 support

### PR DESCRIPTION
**Pull request by chrwei**
adds dallas one wire temp sensor support.  also adds a running median since the DS18s seem to be very susceptible to small changes.  humidity "faked" at 50% due to no sensor (yet)

### CODE REVIEW

**Comment by CuriousTech** [comment]
The probe type is really stable.  I used it on the WiFi waterbed heater project.  When it's between steps, it can jump back and forth, so averaging just a few reads adds a half-step reading, or at least it appears to.

**Comment by chrwei** [comment]
I'd imagine a nice big stable thermal mass like a waterbed would help :)

in air, I noticed when my AC kicked on the temp would drop 4-5 degrees pretty quickly, and then swing back up when the AC turned off.  I didn't test 20 at 5 seconds, but 20 at 15 second intervals matched my commercial thermostat pretty well.

**Comment by CuriousTech** [comment]
Oh, that's what I'm seeing with the SHT21.  I read it at 1Hz on another project and it's really quick to reach the ambient temp, but with the thermostat it might be better to buffer.  I tried closing the vent near it, but that room gets hot.  The commercial thermostat just has air running through it to delay it I think, while mine's sticking out the bottom getting instant readings.

**Comment by chrwei** [comment]
I've also seen the DS jump 5 degrees for one reading and then back.  I'm not sure the cause of that.  at 12bit "borderline" is a fraction of a degree so no biggie.

median solves both, and I suspect it's what commercial thermostats do.

**Comment by CuriousTech** [comment]
I haven't seen the 2 I have jump, but the first read is usually all high bits.  Then it's fine.  With 1-wire, when there's no power it's high, so lows are what actually take power.   I'd suspect the last bit or more is going high sometimes as if it's losing power at the end.  For parasitic, that might happen more often and need more caps or less pullup.

**Pull request merged**
